# Generated by Django 4.2.7 on 2026-01-29 10:11

import core.models.user
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid 10-digit Indian mobile number', regex='^[6-9]\\d{9}$')])),
                ('user_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('collector', 'Collector'), ('admin', 'Admin')], default='customer', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('bike', 'Motorcycle'), ('van', 'Van')], default='bike', max_length=20)),
                ('driving_license', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('current_pickups', models.IntegerField(default=0)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collector',
                'verbose_name_plural': 'Collectors',
                'db_table': 'collectors',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_document', models.FileField(upload_to='vendor_licenses/%Y/%m/')),
                ('license_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ocr_data', models.JSONField(blank=True, default=dict)),
                ('forensics_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('specializations', models.JSONField(default=list)),
                ('processing_capacity', models.IntegerField(default=100)),
                ('current_workload', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_recycled', models.IntegerField(default=0)),
                ('successful_evaluations', models.IntegerField(default=0)),
                ('disputed_evaluations', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('suspension_count', models.IntegerField(default=0)),
                ('last_suspension_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='product_images/%Y/%m/')),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('desktop', 'Desktop PC'), ('battery', 'Battery'), ('monitor', 'Monitor'), ('appliance', 'Appliance'), ('others', 'Others')], max_length=20)),
                ('system_condition_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Classification'), ('classified', 'Classified'), ('vendor_assigned', 'Vendor Assigned'), ('collector_assigned', 'Collector Assigned'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered to Vendor'), ('evaluating', 'Vendor Evaluating'), ('recycled', 'Recycled'), ('disputed', 'Under Dispute')], default='pending', max_length=20)),
                ('system_value_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='core.collector')),
                ('assigned_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_products', to='core.vendor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variance_details', models.JSONField(default=dict)),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('admin_decision', models.CharField(choices=[('pending', 'Pending Review'), ('vendor_correct', 'Vendor Correct'), ('vendor_fraud', 'Vendor Fraud')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flag', to='core.product')),
            ],
            options={
                'verbose_name': 'Fraud Flag',
                'verbose_name_plural': 'Fraud Flags',
                'db_table': 'fraud_flags',
            },
        ),
        migrations.AddField(
            model_name='collector',
            name='permanent_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_collectors', to='core.vendor'),
        ),
        migrations.AddField(
            model_name='collector',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collector_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['verification_status', 'trust_score'], name='vendors_verific_a79e27_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active', 'rating'], name='vendors_is_acti_aa3545_idx'),
        ),
    ]
