# Generated by Django 4.2.7 on 2026-01-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_of_birth_user_phone_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_otp_created_at',
        ),
    ]
