# Generated by Django 4.2.7 on 2026-01-29 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_phone_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='product',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='assigned_collector',
        ),
        migrations.RemoveField(
            model_name='product',
            name='assigned_vendor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='final_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picked_up_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_longitude',
        ),
        migrations.RemoveField(
            model_name='product',
            name='system_condition_score',
        ),
        migrations.RemoveField(
            model_name='product',
            name='system_value_estimate',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unnamed Product', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Upload product image', null=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_approx',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approximate weight in kg', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Pickup'), ('picked', 'Picked Up'), ('recycled', 'Recycled')], default='available', max_length=20),
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location_text', models.CharField(default='Address not provided', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Auto-detected latitude', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Auto-detected longitude', max_digits=11, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('seller_notes', models.TextField(blank=True)),
                ('collector_notes', models.TextField(blank=True)),
                ('collector', models.ForeignKey(blank=True, help_text='Collector assigned to this pickup', limit_choices_to={'user_type': 'collector'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickups', to=settings.AUTH_USER_MODEL)),
                ('product', models.OneToOneField(help_text='The product to be picked up', on_delete=django.db.models.deletion.CASCADE, related_name='pickuprequest', to='core.product')),
                ('seller', models.ForeignKey(help_text='User who requested the pickup', limit_choices_to={'user_type': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category'),
        ),
    ]
